# Use postgres/example user/password credentials
version: '3.1'

services:
  # reverse proxy
  traefik:
    image: traefik/:v2.0.2
  ports:
    # NOTE: according to your traefik-static.yml entryPoints
    - 80:80
    - 443:443
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

